architecture=2,3,1
activation=sigmoid
init_method=xavier
last_optimizer=sgd
last_lr=0.3
last_lr_decay=0
last_momentum=0
last_epochs=5000
last_actual_epochs=5000
last_loss=mse
best_mse=0.062861261
best_epoch=5000
interrupted=0
